apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: nextcloud
    repoURL: https://nextcloud.github.io/helm
    targetRevision: 6.3.0
    helm:
      valuesObject:
        # deploymentAnnotations:
        #     secret.reloader.stakater.com/reload: nextcloud
        nextcloud:
          host: nextcloud.simonemms.com
          trustedDomains:
            - localhost
            - nextcloud.nextcloud.svc.cluster.local
            - nextcloud.simonemms.com
          existingSecret:
            enabled: true
            secretName: nextcloud
            usernameKey: username
            passwordKey: password
          objectStore:
            s3:
              enabled: false
              # enabled: true
              ssl: true
              port: 443
              region: nbg1
              usePathStyle: false
              autoCreate: false
              existingSecret: nextcloud
              prefix: nextcloud/
              secretKeys:
                host: s3-host
                accessKey: s3-access-key
                secretKey: s3-secret-key
                bucket: s3-bucket
        # internalDatabase:
        #   enabled: false
        # externalDatabase:
        #   enabled: true
        # mariadb:
        #   enabled: true
        #   primary:
        #     persistence:
        #       enabled: true
        redis:
          enabled: false
          # enabled: true
          master:
            persistence:
              enabled: false
          replica:
            persistence:
              enabled: false
        ingress:
          enabled: true
          className: nginx
          annotations:
            kubernetes.io/tls-acme: "true"
            cert-manager.io/cluster-issuer: letsencrypt
            gethomepage.dev/description: Nextcloud
            gethomepage.dev/enabled: "true"
            gethomepage.dev/group: Cluster
            gethomepage.dev/icon: nextcloud
            gethomepage.dev/name: Nextcloud
            gethomepage.dev/widget.type: nextcloud
            gethomepage.dev/widget.url: http://nextcloud.nextcloud.svc.cluster.local:8080
            gethomepage.dev/widget.username: "{{HOMEPAGE_VAR_NEXTCLOUD_USERNAME}}"
            gethomepage.dev/widget.password: "{{HOMEPAGE_VAR_NEXTCLOUD_PASSWORD}}"
          tls:
            - hosts:
                - nextcloud.simonemms.com
              secretName: nextcloud-tls
  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
