apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 66.1.1
    helm:
      valuesObject:
        prometheus:
          prometheusSpec:
            additionalScrapeConfigs:
              - job_name: garden
                static_configs:
                  - targets:
                      - garden:3000
              - job_name: greenhouse
                static_configs:
                  - targets:
                      - greenhouse:3000
        grafana:
          admin:
            existingSecret: credentials
          dashboardProviders:
            dashboardproviders.yaml:
              apiVersion: 1
              providers:
                - name: "default"
                  orgId: 1
                  folder: ""
                  type: file
                  disableDeletion: false
                  editable: true
                  options:
                    path: /var/lib/grafana/dashboards/default
          dashboardsConfigMaps:
            default: grafana-dashboards
          grafana.ini:
            server:
              domain: monitoring.simonemms.com
              root_url: "https://%(domain)s"
            auth.github:
              enabled: true
              allow_sign_up: true
              scopes: user:email,read:org
              auth_url: https://github.com/login/oauth/authorize
              token_url: https://github.com/login/oauth/access_token
              api_url: https://api.github.com/user
              team_ids: $__file{/etc/secrets/credentials/githubTeamId}
              allowed_organizations:
                - $__file{/etc/secrets/credentials/githubOrg}
              client_id: $__file{/etc/secrets/credentials/githubClientId}
              client_secret: $__file{/etc/secrets/credentials/githubClientSecret}
          extraSecretMounts:
            - name: credentials
              secretName: credentials
              defaultMode: 0440
              mountPath: /etc/secrets/credentials
              readOnly: true
          persistence:
            enabled: true
            type: statefulset
          podAnnotations:
            configmap.reloader.stakater.com/reload: grafana-dashboards
            secret.reloader.stakater.com/reload: credentials
          ingress:
            enabled: true
            annotations:
              kubernetes.io/tls-acme: "true"
              cert-manager.io/cluster-issuer: letsencrypt
              gethomepage.dev/description: Grafana dashboards
              gethomepage.dev/enabled: "true"
              gethomepage.dev/group: Cluster Management
              gethomepage.dev/icon: grafana
              gethomepage.dev/name: Grafana
            ingressClassName: nginx
            hosts:
              - monitoring.simonemms.com
            tls:
              - hosts:
                  - monitoring.simonemms.com
                secretName: monitoring-tls
          sidecar:
            dashboards:
              enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
