apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: credentials
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  refreshInterval: 10s
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: credentials
    template:
      engineVersion: v2
      data:
        client_id: "{{ .clientId }}"
        client_secret: "{{ .clientSecret }}"
  data:
    - secretKey: clientId
      remoteRef:
        key: OIDC_CLIENT_ID
    - secretKey: clientSecret
      remoteRef:
        key: OIDC_CLIENT_SECRET
