apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: credentials
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  refreshInterval: 10s
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: credentials
    template:
      engineVersion: v2
      data:
        admin-user: admin
        admin-password: "{{ .password }}"
        githubOrg: "{{ .githubOrg }}"
        githubTeamId: "{{ .githubTeamId }}"
        githubClientId: "{{ .githubClientId }}"
        githubClientSecret: "{{ .githubClientSecret }}"
  data:
    - secretKey: password
      remoteRef:
        key: GRAFANA_PASSWORD

    - secretKey: githubOrg
      remoteRef:
        key: GITHUB_ORG

    - secretKey: githubTeamId
      remoteRef:
        key: GITHUB_TEAM_ID

    - secretKey: githubClientId
      remoteRef:
        key: GITHUB_OAUTH_CLIENT_ID

    - secretKey: githubClientSecret
      remoteRef:
        key: GITHUB_OAUTH_CLIENT_SECRET
