apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: credentials
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  refreshInterval: 30s
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: credentials
    template:
      engineVersion: v2
      data:
        admin-user: admin
        admin-password: "{{ .password }}"
        client_id: "{{ .client_id }}"
        client_secret: "{{ .client_secret }}"
  data:
    - secretKey: password
      remoteRef:
        key: GRAFANA_PASSWORD
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: client_id
      remoteRef:
        key: OIDC_CLIENT_ID
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: client_secret
      remoteRef:
        key: OIDC_CLIENT_SECRET
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
