apiVersion: v1
kind: Service
metadata:
  name: greenhouse
  namespace: weather
  labels:
    service: weather
    name: greenhouse
  annotations:
    tailscale.com/tailnet-fqdn: greenhouse.tail30e9d2.ts.net
    argocd.argoproj.io/sync-wave: "10"
spec:
  externalName: greenhouse
  type: ExternalName
  ports:
    - port: 3000
      name: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: greenhouse
  namespace: weather
  labels:
    prometheus: enabled
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  selector:
    matchLabels:
      service: weather
      name: greenhouse
  endpoints:
    - port: metrics
      interval: 15s
