apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: temporal-codec-server-golang
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    chart: temporal-codec-server
    repoURL: ghcr.io/mrsimonemms
    targetRevision: 0.3.4
    helm:
      valuesObject:
        replicaCount: 2
        config:
          corsOrigins:
            - https://cloud.temporal.io
            - http://localhost:8233
        keys:
          createSecret: false
          existingSecret: keys
        podAnnotations:
          secret.reloader.stakater.com/reload: keys
        ingress:
          enabled: true
          host: golang.codec.temporal.simonemms.com
          annotations:
            kubernetes.io/tls-acme: "true"
            cert-manager.io/cluster-issuer: letsencrypt
        resources:
          requests:
            cpu: 10m
            memory: 8Mi
          limits:
            cpu: 25m
            memory: 16Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: temporal-codec-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
