apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keys
  namespace: codec
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  refreshInterval: 30s
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: keys
    template:
      engineVersion: v2
      data:
        # The active key is always in position 0 - anything lower is historical and used only for decryption
        encryption-keys: |-
          - id: "key-1749810806"
            key: {{ .key_1749810806 | quote }}
          # Temporal SA key - the ID and key are the same
          - id: {{ .sa_key | quote }}
            key: {{ .sa_key | quote }}
  data:
    - secretKey: sa_key
      remoteRef:
        key: TEMPORAL_CODEC_SA_KEY
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: key_1749810806
      remoteRef:
        key: TEMPORAL_CODEC_KEY_1749810806
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
