cluster_name: dev
k3s_version: v1.31.1+k3s1
kubeconfig_path: "./kubeconfig"

schedule_workloads_on_masters: true
image: ubuntu-24.04

networking:
  ssh:
    port: 2244
    use_agent: false
    public_key_path: "~/.ssh/homelab.pub"
    private_key_path: "~/.ssh/homelab"
  allowed_networks:
    ssh:
      - 0.0.0.0/0
    api:
      - 0.0.0.0/0
  public_network:
    ipv4: true
    ipv6: true
  private_network:
    enabled: true
    subnet: 10.2.0.0/16
  cni:
    enabled: true
    encryption: false
    mode: flannel

datastore:
  mode: etcd

masters_pool:
  instance_type: cx22
  instance_count: 3
  location: nbg1

worker_node_pools:
  - name: pool1
    instance_type: cx22
    instance_count: 2
    location: nbg1
