tasks:
  - name: Setup
    before: |
      curl -sfL gpm.simonemms.com | bash

      gpm install pre-commit yq

      pip install cookieninja cruft

      wget https://github.com/vitobotta/hetzner-k3s/releases/download/v1.1.5/hetzner-k3s-linux-amd64
      chmod +x hetzner-k3s-linux-amd64
      sudo mv hetzner-k3s-linux-amd64 /usr/local/bin/hetzner-k3s

      gp sync-done setup

      pre-commit install --install-hooks -t pre-commit -t commit-msg

      gp sync-done pre-commit

      exit 0
  - command: |
      gp sync-await setup

vscode:
  extensions:
    - donjayamanne.git-extension-pack
    - EditorConfig.EditorConfig
    - waderyan.gitblame
    - GitHub.vscode-github-actions
    - ms-vscode.makefile-tools
