apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.11.3
    helm:
      valuesObject:
        controller:
          # Not strictly necessary, but feels safer running on all nodes
          kind: DaemonSet
          config:
            use-proxy-protocol: false
          extraArgs:
            enable-ssl-passthrough: true
          service:
            annotations:
              metallb.universe.tf/allow-shared-ip: primary
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
