apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argo-server-sso
  namespace: argo-workflows
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  refreshInterval: 30s
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: argo-server-sso
  data:
    - secretKey: client-id
      remoteRef:
        key: OIDC_CLIENT_ID
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: client-secret
      remoteRef:
        key: OIDC_CLIENT_SECRET
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
