apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: reloader
    repoURL: https://stakater.github.io/stakater-charts
    targetRevision: 1.2.0
    helm:
      valuesObject:
        reloader:
          # @link https://github.com/argoproj/argo-cd/discussions/14183
          reloadStrategy: annotations
          podMonitor:
            enabled: true
            labels:
              prometheus: enabled
          watchGlobally: true
          deployment:
            resources:
              requests:
                cpu: 25m
                memory: 50Mi
              limits:
                cpu: 50m
                memory: 100Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: reloader
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
