apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mrsimonemms/infrastructure
    path: registry/components/argo-workflows
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-workflows
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
