apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole-ingress-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mrsimonemms/infrastructure
    path: registry/components/pihole-ingress
    targetRevision: sje/hetzner-k3s
  destination:
    server: https://kubernetes.default.svc
    namespace: pihole
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - kind: Service
      namespace: pihole
      jsonPointers:
        - /spec/externalName
