apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: temporal-codec-server-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mrsimonemms/infrastructure
    path: registry/components/temporal-codec-server
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: temporal-codec-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
