apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: nodes
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "20"
