---
# Use a fake secret so that Kustomize only needs to update in a single place
apiVersion: generators.external-secrets.io/v1alpha1
kind: Fake
metadata:
  name: oidc-settings
  namespace: dex
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  data:
    base_url: https://oidc.dev.simonemms.com
    argocd_url: https://argocd.dev.simonemms.com
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: config
  namespace: dex
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  refreshInterval: 10s
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: config
    template:
      engineVersion: v2
      data:
        config.yaml: |-
          issuer: {{ .base_url }}
          storage:
            type: memory
          staticClients:
            - name: infrastructure
              id: {{ .oidc_client_id }}
              secret: {{ .oidc_client_secret }}
              redirectURIs:
                - {{ .argocd_url }}/auth/callback
          connectors:
            - type: github
              id: github
              name: GitHub
              config:
                clientID: {{ .github_client_id }}
                clientSecret: {{ .github_client_secret }}
                redirectURI: {{ .base_url }}/callback
                orgs:
                  - name: mrsimonemmsorg
                    teams:
                      - home-admin
          oauth2:
            skipApprovalScreen: true
  data:
    - secretKey: github_client_id
      remoteRef:
        key: GITHUB_OAUTH_CLIENT_ID
    - secretKey: github_client_secret
      remoteRef:
        key: GITHUB_OAUTH_CLIENT_SECRET
    - secretKey: oidc_client_id
      remoteRef:
        key: OIDC_CLIENT_ID
    - secretKey: oidc_client_secret
      remoteRef:
        key: OIDC_CLIENT_SECRET
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Fake
          name: oidc-settings
