apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mrsimonemms/infrastructure
    path: registry/components/tailscale
    targetRevision: sje/hetzner-k3s
    kustomize:
      patches:
        - target:
            group: argoproj.io
            version: v1alpha1
            kind: Application
            name: tailscale
          patch: |-
            - op: replace
              path: /spec/source/helm/valuesObject/operatorConfig/hostname
              value: kubernetes-cluster-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
