apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dex-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mrsimonemms/infrastructure
    path: registry/components/dex
    targetRevision: sje/hetzner-k3s
    kustomize:
      patches:
        - target:
            group: argoproj.io
            version: v1alpha1
            kind: Application
            name: dex
          patch: |-
            - op: replace
              path: /spec/source/helm/valuesObject/ingress/hosts/0/host
              value: oidc.dev.simonemms.com
            - op: replace
              path: /spec/source/helm/valuesObject/ingress/tls/0/hosts/0
              value: oidc.dev.simonemms.com
            - op: replace
              path: /spec/source/helm/valuesObject/ingress/annotations/cert-manager.io~1cluster-issuer
              value: letsencrypt-staging
        - target:
            group: generators.external-secrets.io
            version: v1alpha1
            kind: Fake
            name: oidc-settings
          patch: |-
            - op: replace
              path: /spec/data/base_url
              value: https://oidc.dev.simonemms.com
            - op: replace
              path: /spec/data/argocd_url
              value: https://argocd.dev.simonemms.com
            - op: replace
              path: /spec/data/homepage_url
              value: https://homepage.dev.simonemms.com
  destination:
    server: https://kubernetes.default.svc
    namespace: dex
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - kind: Service
      namespace: dex
      jsonPointers:
        - /spec/externalName
