apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: temporal-codec-server-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mrsimonemms/infrastructure
    path: registry/components/temporal-codec-server
    targetRevision: HEAD
    kustomize:
      patches:
        - target:
            group: argoproj.io
            version: v1alpha1
            kind: Application
            name: temporal-codec-server
          patch: |-
            - op: replace
              path: /spec/source/helm/valuesObject/ingress/host
              value: golang.codec.temporal.dev.simonemms.com
            - op: replace
              path: /spec/source/helm/valuesObject/ingress/annotations/cert-manager.io~1cluster-issuer
              value: letsencrypt-staging
  destination:
    server: https://kubernetes.default.svc
    namespace: temporal-codec-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
