apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mrsimonemms/infrastructure
    path: registry/components/external-secrets
    targetRevision: HEAD
    kustomize:
      patches:
        - target:
            group: external-secrets.io
            version: v1beta1
            kind: ClusterSecretStore
            name: infisical
          patch: |-
            - op: replace
              path: /spec/provider/infisical/secretsScope/environmentSlug
              value: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
