apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mrsimonemms/infrastructure
    path: registry/components/monitoring
    targetRevision: HEAD
    kustomize:
      patches:
        - target:
            group: argoproj.io
            version: v1alpha1
            kind: Application
            name: monitoring
          patch: |-
            - op: replace
              path: /spec/source/helm/valuesObject/grafana/ingress/hosts/0
              value: grafana.dev.simonemms.com
            - op: replace
              path: /spec/source/helm/valuesObject/grafana/ingress/tls/0/hosts/0
              value: grafana.dev.simonemms.com
            - op: replace
              path: /spec/source/helm/valuesObject/grafana/grafana.ini/server/domain
              value: grafana.dev.simonemms.com
            - op: replace
              path: /spec/source/helm/valuesObject/grafana/ingress/annotations/cert-manager.io~1cluster-issuer
              value: letsencrypt-staging
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - kind: Service
      namespace: monitoring
      jsonPointers:
        - /spec/externalName
