apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mrsimonemms/infrastructure
    path: registry/components/pihole
    targetRevision: HEAD
    kustomize:
      patches:
        - target:
            group: argoproj.io
            version: v1alpha1
            kind: Application
            name: pihole
          patch: |-
            - op: replace
              path: /spec/source/helm/valuesObject/virtualHost
              value: pihole.dev.simonemms.com
        - target:
            group: argoproj.io
            version: v1alpha1
            kind: Application
            name: pihole
          patch: |-
            - op: replace
              path: /spec/source/helm/valuesObject/ingress/annotations/cert-manager.io~1cluster-issuer
              value: letsencrypt-staging
        - target:
            group: argoproj.io
            version: v1alpha1
            kind: Application
            name: pihole
          patch: |-
            - op: replace
              path: /spec/source/helm/valuesObject/ingress/hosts/0
              value: pihole.dev.simonemms.com
        - target:
            group: argoproj.io
            version: v1alpha1
            kind: Application
            name: pihole
          patch: |-
            - op: replace
              path: /spec/source/helm/valuesObject/ingress/tls/0/hosts/0
              value: pihole.dev.simonemms.com
  destination:
    server: https://kubernetes.default.svc
    namespace: pihole
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
