apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fission
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: fission-all
    repoURL: https://fission.github.io/fission-charts
    targetRevision: v1.20.5
    helm:
      valuesObject:
        analytics: false
  destination:
    server: https://kubernetes.default.svc
    namespace: fission
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
