apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fission-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: crds/v1
    repoURL: https://github.com/fission/fission
    targetRevision: v1.20.5
  destination:
    server: https://kubernetes.default.svc
    namespace: fission
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
