apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-rbac
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    path: deploy/rbac
    repoURL: https://github.com/bank-vaults/vault-operator
    targetRevision: HEAD
    kustomize:
      namespace: vault
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
