apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-toolkit
  namespace: vault
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-toolkit
  namespace: vault
rules:
  - apiGroups:
      - ""
      - extensions
      - apps
    resources:
     - pods
    verbs:
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-toolkit
  namespace: vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-toolkit
subjects:
  - kind: ServiceAccount
    name: k8s-toolkit
    namespace: vault
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "99"
  name: vault-wait
  namespace: vault
spec:
  template:
    spec:
      containers:
        - args:
            - wait
            - -n
            - vault
            - -l
            - app.kubernetes.io/name=vault
            - pod
            - --for=condition=Ready
            - --timeout
            - 10m
          image: bitnami/kubectl:1.31
          imagePullPolicy: IfNotPresent
          name: wait
      restartPolicy: OnFailure
      serviceAccountName: k8s-toolkit
