apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  refreshInterval: 30s
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: cloudflare
  data:
    - secretKey: cloudflare_api_token
      remoteRef:
        key: CLOUDFLARE_API_TOKEN
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
