apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "20"
spec:
  provider:
    bitwardensecretsmanager:
      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden
            namespace: external-secrets
      caProvider:
        type: Secret
        name: root-secret
        namespace: cert-manager
        key: ca.crt
      bitwardenServerSDKURL: https://bitwarden-sdk-server:9998
      organizationID: ecbdd8af-5694-4019-a29a-b2c9009e2e1d
      projectID: 0a52cfc7-3446-48fd-bfea-b2fb009cbf48
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bitwarden-sdk
  namespace: external-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  secretName: bitwarden-tls-certs
  dnsNames:
    - bitwarden-sdk-server.external-secrets.svc.cluster.local
    - bitwarden-sdk-server
  issuerRef:
    name: internal
    kind: ClusterIssuer
    group: cert-manager.io
