apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: credentials
  namespace: gotify
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  refreshInterval: 10s
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: credentials
    template:
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        token: Basic {{ print .username ":" .password | b64enc }}
  data:
    - secretKey: username
      remoteRef:
        key: GOTIFY_USERNAME
    - secretKey: password
      remoteRef:
        key: GOTIFY_PASSWORD
