apiVersion: batch/v1
kind: Job
metadata:
  name: setup
  namespace: gotify
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 30
  backoffLimit: 3
  template:
    spec:
      containers:
        - name: apps
          image: alpine/curl:8.10.0
          command:
            - sh
            - -c
          args:
            - 'curl -s ${APP_URL}/application -H "Authorization: ${AUTH}" | grep -q "Get iPlayer" || curl -X POST -s ${APP_URL}/application -H "Authorization: ${AUTH}" -H "Content-Type: application/json" -d "${APPLICATION_DATA}"'
          env:
            - name: APPLICATION_DATA
              value: |
                { "defaultPriority": 1, "description": "Trigger Get iPlayer workflow", "name": "Get iPlayer" }
            - name: APP_URL
              value: http://gotify:8080
            - name: AUTH
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: token
      restartPolicy: Never
