kubeconfig_path: ./kubeconfig
public_ssh_key_path: ~/.ssh/key.pub
private_ssh_key_path: ~/.ssh/key
use_ssh_agent: false
ssh_port: 22
ssh_allowed_networks:
  - 0.0.0.0/0
api_allowed_networks:
  - 0.0.0.0/0
private_network_subnet: 10.0.0.0/16
disable_flannel: false
schedule_workloads_on_masters: false
enable_public_net_ipv4: true
enable_public_net_ipv6: true
image: ubuntu-22.04
cloud_controller_manager_manifest_url: https://github.com/hetznercloud/hcloud-cloud-controller-manager/releases/download/v1.18.0/ccm-networks.yaml
csi_driver_manifest_url: https://raw.githubusercontent.com/hetznercloud/csi-driver/v2.5.1/deploy/kubernetes/hcloud-csi.yml
system_upgrade_controller_manifest_url: https://raw.githubusercontent.com/rancher/system-upgrade-controller/master/manifests/system-upgrade-controller.yaml
masters_pool:
  instance_type: cx21
  instance_count: 3
  location: nbg1
worker_node_pools: []
