apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unifi
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    chart: unifi
    repoURL: https://k8s-at-home.com/charts/
    targetRevision: 5.1.2
    helm:
      valuesObject:
        image:
          repository: ghcr.io/jacobalberty/unifi-docker
          tag: v9.2.87
        env:
          JVM_INIT_HEAP_SIZE: 512M
          JVM_MAX_HEAP_SIZE: 512M
          JVM_MAX_THREAD_STACK_SIZE: 512M
          UNIFI_STDOUT: "true"
        resources:
          requests:
            cpu: 1
            memory: 512Mi
          limits:
            cpu: 2
            memory: 1024Mi
        service:
          main:
            annotations:
              metallb.universe.tf/allow-shared-ip: primary
            type: LoadBalancer
          udp:
            enabled: false
            type: LoadBalancer
            annotations:
              metallb.universe.tf/allow-shared-ip: primary
            ports:
              stun:
                enabled: true
                port: 3478
                protocol: UDP
              syslog:
                enabled: true
                port: 5514
                protocol: UDP
              discovery:
                enabled: true
                port: 10001
                protocol: UDP
        ingress:
          main:
            enabled: true
            annotations:
              kubernetes.io/tls-acme: "true"
              cert-manager.io/cluster-issuer: letsencrypt
              gethomepage.dev/description: Unifi network control panel
              gethomepage.dev/enabled: "true"
              gethomepage.dev/group: Cluster
              gethomepage.dev/icon: unifi
              gethomepage.dev/name: Unifi
              gethomepage.dev/widget.type: unifi
              gethomepage.dev/widget.url: https://unifi.simonemms.com
              gethomepage.dev/widget.username: "{{HOMEPAGE_VAR_UNIFI_USERNAME}}"
              gethomepage.dev/widget.password: "{{HOMEPAGE_VAR_UNIFI_PASSWORD}}"
            ingressClassName: nginx
            hosts:
              - host: unifi.simonemms.com
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - hosts:
                  - unifi.simonemms.com
                secretName: unifi-tls
        persistence:
          data:
            enabled: true
            accessMode: ReadWriteOnce
            size: 10Gi
        mongodb:
          enabled: true
          useStatefulSet: true
          resources:
            requests:
              cpu: 1
              memory: 512Mi
            limits:
              cpu: 2
              memory: 1024Mi
          persistence:
            enabled: true
            size: 10Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: unifi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
