apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: s3-creds
  namespace: unifi
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  refreshInterval: 10s
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: s3-creds
    template:
      engineVersion: v2
      data:
        client_id: "{{ .access_key_id }}"
        client_secret: "{{ .secret_access_key }}"
        host: "{{ .host }}"
        alias_host: "https://{{ .access_key_id }}:{{ .secret_access_key }}@{{ .host }}"
  data:
    - secretKey: access_key_id
      remoteRef:
        key: S3_ACCESS_KEY_ID
    - secretKey: secret_access_key
      remoteRef:
        key: S3_SECRET_ACCESS_KEY
    - secretKey: host
      remoteRef:
        key: S3_HOST
