apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unifi-poller
  namespace: unifi
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  refreshInterval: 10s
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: unifi-poller
  data:
    - secretKey: username
      remoteRef:
        key: UNIFI_CONTROLLER_READONLY_USERNAME
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: password
      remoteRef:
        key: UNIFI_CONTROLLER_READONLY_PASSWORD
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
