# This secret is created by Terraform, but the external-secret is to manage drift
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oidc
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  refreshInterval: 10s
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: oidc
  data:
    - secretKey: clientId
      remoteRef:
        key: OIDC_CLIENT_ID
    - secretKey: clientSecret
      remoteRef:
        key: OIDC_CLIENT_SECRET
