apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: homepage
    repoURL: https://jameswynn.github.io/helm-charts
    targetRevision: 2.0.1
    helm:
      valuesObject:
        image:
          tag: v0.9.13
        controller:
          annotations:
            configmap.reloader.stakater.com/reload: homepage
            secret.reloader.stakater.com/reload: homepage-secrets
          replicas: 2
        podAnnotations:
          reloader.argo: dummy
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 2000m
            memory: 1Gi
        config:
          useExistingConfigMap: homepage
        enableRbac: true
        envFrom:
          - secretRef:
              name: homepage-secrets
        ingress:
          main:
            enabled: true
            annotations:
              kubernetes.io/tls-acme: "true"
              cert-manager.io/cluster-issuer: letsencrypt
              nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
              nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
              nginx.ingress.kubernetes.io/affinity: cookie
              nginx.ingress.kubernetes.io/affinity-mode: persistent
              nginx.ingress.kubernetes.io/session-cookie-secure: "true"
              nginx.ingress.kubernetes.io/session-cookie-change-on-failure: "true"
            ingressClassName: nginx
            hosts:
              - host: homepage.simonemms.com
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - hosts:
                  - homepage.simonemms.com
                secretName: homepage-tls
  destination:
    server: https://kubernetes.default.svc
    namespace: homepage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
