apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: homepage
    repoURL: https://jameswynn.github.io/helm-charts
    targetRevision: 2.0.1
    plugin:
      name: kustomized-helm
    helm:
      valuesObject:
        image:
          tag: v0.9.13
        controller:
          annotations:
            configmap.reloader.stakater.com/reload: homepage
        config:
          useExistingConfigMap: homepage
        enableRbac: true
        ingress:
          main:
            enabled: true
            annotations:
              kubernetes.io/tls-acme: "true"
              cert-manager.io/cluster-issuer: letsencrypt
            ingressClassName: nginx
            hosts:
              - host: homepage.simonemms.com
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - hosts:
                  - homepage.simonemms.com
                secretName: homepage-tls
  destination:
    server: https://kubernetes.default.svc
    namespace: homepage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
