apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - all.yaml
  - configmap.yaml
  - namespace.yaml
# patchesJson6902:
#   - target:
#       group: apps
#       version: v1
#       kind: Deployment
#       name: homepage
#     patch: |-
#       - op: replace
#         path: /spec/replicas
#         value: 2
helmCharts:
  - valuesInline:
      image:
        tag: v0.9.13
      controller:
        annotations:
          configmap.reloader.stakater.com/reload: homepage
      config:
        useExistingConfigMap: homepage
      enableRbac: true
      ingress:
        main:
          enabled: true
          annotations:
            kubernetes.io/tls-acme: "true"
            cert-manager.io/cluster-issuer: letsencrypt-staging
          ingressClassName: nginx
          hosts:
            - host: homepage.dev.simonemms.com
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - homepage.dev.simonemms.com
              secretName: homepage-tls
