apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - all.yaml
  - configmap.yaml
  - namespace.yaml
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: homepage
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
