apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: basic-auth
  namespace: homepage
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  refreshInterval: 10s
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: basic-auth
  data:
    - secretKey: auth
      remoteRef:
        key: HOMEPAGE_PASSWORD
