apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage-secrets
  namespace: homepage
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  refreshInterval: 10s
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: homepage-secrets
  data:
    - secretKey: HOMEPAGE_VAR_NEXTCLOUD_USERNAME
      remoteRef:
        key: NEXTCLOUD_ADMIN_USERNAME
    - secretKey: HOMEPAGE_VAR_NEXTCLOUD_PASSWORD
      remoteRef:
        key: NEXTCLOUD_ADMIN_PASSWORD
    - secretKey: HOMEPAGE_VAR_ARGOCD_KEY
      remoteRef:
        key: ARGOCD_HOMEPAGE_TOKEN
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: HOMEPAGE_VAR_CALENDAR_SIMONEMMS_GMAIL_COM
      remoteRef:
        key: CALENDAR_SIMONEMMS_GMAIL_COM
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: HOMEPAGE_VAR_CALENDAR_SIMON_SIMONEMMS_COM
      remoteRef:
        key: CALENDAR_SIMON_SIMONEMMS_COM
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: HOMEPAGE_VAR_CALENDAR_SIMON_KONSTRUCT_IO
      remoteRef:
        key: CALENDAR_SIMON_KONSTRUCT_IO
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: HOMEPAGE_VAR_GRAFANA_PASSWORD
      remoteRef:
        key: GRAFANA_PASSWORD
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: HOMEPAGE_VAR_PIHOLE_API_KEY
      remoteRef:
        key: PIHOLE_API_KEY
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: HOMEPAGE_VAR_UNIFI_USERNAME
      remoteRef:
        key: UNIFI_CONTROLLER_READONLY_USERNAME
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: HOMEPAGE_VAR_UNIFI_PASSWORD
      remoteRef:
        key: UNIFI_CONTROLLER_READONLY_PASSWORD
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
