apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: temporal
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    chart: temporal
    repoURL: https://go.temporal.io/helm-charts
    targetRevision: 0.63.0
    helm:
      valuesObject:
        cassandra:
          enabled: false
        elasticsearch:
          enabled: false
        grafana:
          enabled: false
        prometheus:
          enabled: false
        schema:
          createDatabase:
            enabled: true
          setup:
            enabled: true
          update:
            enabled: true
        server:
          replicaCount: 1
          config:
            namespaces:
              create: true
              namespace:
                - name: default
                  retention: 7d
            persistence:
              default:
                driver: sql
                sql:
                  driver: mysql8
                  host: temporal-mysql
                  port: 3306
                  database: temporal
                  user: root
                  existingSecret: mysql
                  maxConns: 20
                  maxIdleConns: 20
                  maxConnLifetime: 1h
              visibility:
                driver: sql
                sql:
                  driver: mysql8
                  host: temporal-mysql
                  port: 3306
                  database: temporal_visibility
                  user: root
                  existingSecret: mysql
                  maxConns: 20
                  maxIdleConns: 20
                  maxConnLifetime: 1h
  destination:
    server: https://kubernetes.default.svc
    namespace: temporal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
