apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: temporal-mysql
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    chart: mysql
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 13.0.2
    helm:
      valuesObject:
        global:
          defaultStorageClass: hcloud-volumes
        auth:
          createDatabase: false
          database: temporal
          existingSecret: mysql
        primary:
          persistence:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: temporal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
