apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: mysql-password
  namespace: temporal
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  length: 42
  digits: 5
  symbols: 5
  symbolCharacters: "-_$@"
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql
  namespace: temporal
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  refreshInterval: "30m"
  target:
    name: mysql
    template:
      engineVersion: v2
      data:
        # @todo(sje): create unique passwords for each of these
        mysql-root-password: "{{ .password }}"
        mysql-replication-password: "{{ .password }}"
        mysql-password: "{{ .password }}"
        # Used by Temporal
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: mysql-password
