apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: password
  namespace: pihole
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  refreshInterval: 10s
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: password
  data:
    - secretKey: password
      remoteRef:
        key: PIHOLE_PASSWORD
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
