#cloud-config

package_reboot_if_required: true
package_update: true
package_upgrade: true
packages:
  - curl
runcmd:
  - [service, sshd, restart]
  - [rm, -f, /root/.ssh/authorized_keys]
  - chown ${user}:${user} "/home/${user}"
  - curl -sfL ${k3s_download_url} | INSTALL_K3S_EXEC="agent" sh -
timezone: UTC
users:
  - default
  - name: "${user}"
    gecos: "${user}"
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: true
    shell: /bin/bash
    ssh_authorized_keys:
      - "${chomp(publicKey)}"
write_files:
  - path: /etc/ssh/sshd_config.d/ssh.conf
    content: |
      PasswordAuthentication no
      PermitRootLogin no
      Port ${sshPort}
  - path: /etc/environment
    content: |
      KUBECONFIG="/etc/rancher/k3s/k3s.yaml"
    append: true
  - path: /etc/rancher/k3s/config.yaml
    content: |
      ${indent(6, yamlencode(k3s_config))}
