global:
  domain: ${domain}
controller:
  emptyDir:
    sizeLimit: 500Mi
redis-ha:
  enabled: true
repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2
  extraContainers:
    - name: kustomized-helm
      image: '{{ default .Values.global.image.repository .Values.repoServer.image.repository }}:{{ default (include "argo-cd.defaultTag" .) .Values.repoServer.image.tag }}'
      command:
        - argocd-cmp-server
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop:
            - ALL
      volumeMounts:
        - name: plugins
          mountPath: /home/argocd/cmp-server/plugins
        - name: cmp-kustomized-helm
          mountPath: /home/argocd/cmp-server/config/plugin.yaml
          subPath: kustomized-helm.yaml
        - mountPath: /tmp
          name: cmp-tmp
  volumes:
    - name: cmp-kustomized-helm
      configMap:
        name: argocd-cmp-cm
    - name: cmp-tmp
      emptyDir: {}
server:
  autoscaling:
    enabled: true
    minReplicas: 2
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: ${cluster_issuer}
      gethomepage.dev/description: Get stuff done with Kubernetes!
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: Cluster Management
      gethomepage.dev/icon: argocd
      gethomepage.dev/name: ArgoCD
    tls: true
    extraTLS:
      - hosts:
          - ${domain}
        secretName: argocd-tls
configs:
  cm:
    admin.enabled: false
    dex.config: |-
      ${indent(6, yamlencode(dex_config))}
    kustomize.buildOptions: --enable-helm --load-restrictor=LoadRestrictionsNone
    statusbadge.enabled: true
    url: https://${domain}
  cmp:
    create: true
    plugins:
      kustomized-helm:
        generate:
          command:
            - /bin/sh
            - -c
          args:
            - kustomize build --enable-helm
  params:
    server.insecure: true
  rbac:
    create: true
    policy.csv: |
      ${indent(6, policy)}
