global:
  domain: ${domain}
redis-ha:
  # enabled: true
  enabled: false
repoServer:
  autoscaling:
    # enabled: true
    enabled: false
    minReplicas: 2
server:
  autoscaling:
    # enabled: true
    enabled: false
    minReplicas: 2
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: ${cluster_issuer}
    tls: true
    extraTLS:
      - hosts:
          - ${domain}
        secretName: argocd-tls
configs:
  cm:
    admin.enabled: false
    dex.config: |-
      ${indent(6, yamlencode(dex_config))}
    statusbadge.enabled: true
    url: https://${domain}
  params:
    server.insecure: true
