global:
  domain: ${domain}
controller:
  emptyDir:
    sizeLimit: 500Mi
redis-ha:
  enabled: true
repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2
server:
  autoscaling:
    enabled: true
    minReplicas: 2
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: ${cluster_issuer}
      gethomepage.dev/description: Get stuff done with Kubernetes!
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: Cluster Management
      gethomepage.dev/icon: argocd
      gethomepage.dev/name: ArgoCD
    tls: true
    extraTLS:
      - hosts:
          - ${domain}
        secretName: argocd-tls
configs:
  cm:
    admin.enabled: false
    dex.config: |-
      ${indent(6, yamlencode(dex_config))}
    kustomize.buildOptions: --enable-helm
    statusbadge.enabled: true
    url: https://${domain}
  cmp:
    create: true
    plugins:
      kustomized-helm:
        init:
          command:
            - /bin/sh
            - -c
          args:
            - helm dependency build || true
        generate:
          command:
            - /bin/sh
            - -c
          args:
            - helm template . --name-template $${ARGOCD_APP_NAME} --namespace $${ARGOCD_APP_NAMESPACE} --include-crds > all.yaml && kustomize build
  params:
    server.insecure: true
  rbac:
    create: true
    policy.csv: |
      ${indent(6, policy)}
  repoServer:
