name: Deploy
on:
  - pull_request
permissions:
  pull-requests: write
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
  TF_TOKEN_app_terraform_io: ${{ secrets.TERRAFORM_CLOUD_SECRET }}
  TF_VAR_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
  TF_VAR_ssh_key: ${{ secrets.SSH_KEY_PRIVATE }}
  TF_VAR_ssh_key_public: ${{ secrets.SSH_KEY_PUBLIC }}
  TF_VERSION: '1.9.3'
  TG_VERSION: '0.66.1'
  WORKING_DIR: stacks/prod
jobs:
  plan:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v4

      - name: Plan
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.TF_VERSION }}
          tg_version: ${{ env.TG_VERSION }}
          tg_dir: ${{ env.WORKING_DIR }}
          tg_command: run-all plan
          tg_comment: 1

  deploy:
    runs-on: ubuntu-latest
    needs:
      - plan
    environment: prod
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.TF_VERSION }}
          tg_version: ${{ env.TG_VERSION }}
          tg_dir: ${{ env.WORKING_DIR }}
          tg_command: run-all apply
